### ISSUE TITLE
Data Preprocessing Time

### ISSUE THREAD

**Issue by XiaolongTang23** [MCZhi/DTPP#18]
Hello, I have a question regarding the data preprocessing time. How long does the entire data preprocessing usually take? I tried preprocessing the data on the val split, and it took around 180 hours. Is this normal?

**Comment by MCZhi** [comment]
Hi, @XiaolongTang23. If you want to process the entire data on the val or test split, it would usually take a long time. We recommend using only a subset of the validation split, which takes less time and still provides acceptable performance. We have found that multithreading cannot accelerate the process due to the bottleneck when loading the database files.
