### ISSUE TITLE
 use own collected data 

### ISSUE THREAD

**Issue by StephenGordan** [MCZhi/DTPP#7]
Thank you for your fantastic work.！
I have a question I'd like to ask.
How to create a dataset similar to nuPlan from my own collected data for model training？

**Comment by MCZhi** [comment]
Hi, @StephenGordan, thank you for your interest. The model requires two types of inputs: agents' tracks (object detection states) and map polylines (vectorized HD map). In order to train and test the model with your own collected dataset, you will need to convert the raw data into these two datatypes and then proceed with training the model.
